//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PrimaryPhone { get; set; }
        public string SecondaryPhone { get; set; }
        public Nullable<int> CurrentState { get; set; }
        public Nullable<int> CurrentCity { get; set; }
        public string CurrentAddress { get; set; }
        public Nullable<bool> IsAddressSame { get; set; }
        public Nullable<int> PermanentState { get; set; }
        public Nullable<int> PermanentCity { get; set; }
        public string PermanentAddress { get; set; }
        public Nullable<long> AadhaarNumber { get; set; }
        public string PanCardNumber { get; set; }
        public string UploadAadhaar { get; set; }
        public string UploadPanCard { get; set; }
    }
}
